### ISSUE TITLE
Syndicate 2012 sounds

### ISSUE THREAD

**Issue by JulesMerit** [Metastruct/garrysmod-chatsounds#102]
[syndicate 2012.zip sounds](https://github.com/Metastruct/garrysmod-chatsounds/files/923883/syndicate.2012.zip)

there is three sounds:
"ramon_youstillbreathing" - must work when says "you still breathing down there?"
"ramon_imwiredtoo" - must work when says "im wired too"
"julesmerit_emotion" - must work with other chatsounds "shit", like "shit#12" or both.

**Comment by PotcFdk** [comment]
The emotion one sounds incomplete to me.

**Comment by PotcFdk** [comment]
To the reviewer; here are ogg versions.

[syndicate.2012.ogg.zip](https://github.com/Metastruct/garrysmod-chatsounds/files/950175/syndicate.2012.ogg.zip)

**Comment by Noiwex** [comment]
Create a proper pull request with these sounds in a special folder.
