### ISSUE TITLE
Well hey there young man. Welcome to FurAffinity! Are you ready to yiff? YEAAAAAH!

### ISSUE THREAD

**Issue by notcake** [Metastruct/garrysmod-chatsounds#11]
https://soundcloud.com/dbpony/wanna-yiff

**Comment by ukgamer** [comment]
URGENT PLEASE FIX ASAP

**Comment by PotcFdk** [comment]
Cookie, cookie, eat a cookie.

**Comment by ukgamer** [comment]
WHY ISN'T THIS FIXED

**Comment by ukgamer** [comment]
I'M DOCKING YOUR PAY

**Comment by ArcticFqx** [comment]
![Yiff](https://i1.sndcdn.com/artworks-000067856571-upbdza-t500x500.jpg)

**Comment by ukgamer** [comment]
:3

**Comment by mitterdoo** [comment]
stahp my inbox is suffering

**Comment by TheKeyLimePie** [comment]
CAN HAS FIX FIX FIX FIX PLZZZ??!?!?!
