### ISSUE TITLE
Meet the Heavy

### ISSUE THREAD

**Issue by SpiralP** [Metastruct/garrysmod-chatsounds#148]
https://www.youtube.com/watch?v=jHgZh4GV9G0
oh my god who touched sasha
alright who touched my gun
i have yet to meet one that can outsmart boolet
etc

**Comment by aminpeck** [comment]
Addressed with revision 2711.

**Comment by PotcFdk** [comment]
(he meant cf856f6a54f87aa942ddd2c7e5f71344dba8167e)
