### ISSUE TITLE
new added chatsounds

### ISSUE THREAD

**Issue by bjoern90** [Metastruct/garrysmod-chatsounds#197]
new added chatsounds wont auto load when doing !newchatsounds anymore and whenever using the convar "goluwa_clear_cache" it can crash clients.. is something wrong? or did some devs do a bad shit to chatsounds?

**Comment by PotcFdk** [comment]
Might be related to [this](https://github.com/Metastruct/issues/issues/399), but in any case this repo is not the one that deals with the "newchatsounds" code.
https://github.com/PAC3-Server/notagain
