### ISSUE TITLE
disable playing of random words if sentences has no match

### ISSUE THREAD

**Issue by X-Coder** [Metastruct/garrysmod-chatsounds#21]
Hi, I like this addon and want to use it on my server.

On my server people are allowed to speak in their foreign languages.
Lot speak english or german, some france.

The problem I currently have is, if someone writes a whole sentence, and the addon can't find a match on the whole sentence, it splits the sentences into its words and tries to find sub-matches and plays them, which sounds kind of strange and begins to suck a little, because it sounds like hiccup.

A option to disable this "sub-match-playing" would be great, so it only plays sounds if it can find full match across the whole sentence. Maybe only if modifiers are being used, allow sub-match-playing.

Tried to modify the lua files myself, but it seems not so easy as it sounds. I hoped you could give me a little help or a hint/patchfile whats need to be changed.

**Comment by notcake** [comment]
Abandon hope, all ye who enter here.

**Comment by Python1320** [comment]
I take that you want only those messages to play that are whole chatsounds only as in "Hello world" should not play world.wav or hello.wav but if there is "hello world.wav" then it should play.
:dragon_face:

**Comment by X-Coder** [comment]
Yes this is what I meant, a option to disable single word playing (if no modifiers used).
Or only play a sound if the autocomplete-text fully matches the entered text in chat.

**Comment by Noiwex** [comment]
Not going to happen.
