### ISSUE TITLE
bug LCL?

### ISSUE THREAD

**Issue by X-Coder** [Metastruct/garrysmod-chatsounds#22]
Shouldn't this be "LUA" instead of "LCL"? Is LCL even valid?
https://github.com/Metastruct/garrysmod-chatsounds/blob/master/lua/chatsounds/cl_core.lua#L334

**Comment by Techbot121** [comment]
iirc there is lsv too, so I guess it's just an alias.

**Comment by PotcFdk** [comment]
`LCL` and `LUA` return different things:
![demonstration](https://threekelv.in/~potcfdk/tmp/2015-07-18_18-53-50.png)
