### ISSUE TITLE
added streaming

### ISSUE THREAD

**Issue by X-Coder** [Metastruct/garrysmod-chatsounds#23]
Maybe I'm just dumb, but I couldn't figure out how the playing of the lists_nosend files is currently supposed to work if the client hasn't downloaded all the sound files before.

So I added direct streaming from a apache like webserver in this commit 5aa28759fd85343ce4f8fa40eb10cfb51d13265d, if you are interested.

You need to define your URL of the hosted files inside the top of cl_core.lua file.

Just make a good test before using it, because it might have break some things.
The modifiers doesn't work with this yet, but at least it streams from my webserver, using gmod's internal BASS.

**Comment by PotcFdk** [comment]
The situation that you described in your first sentence is how it's meant to work; how it was designed.
Several issues can arise when you begin streaming sound files, including, but not limited to
* Latency
* Increased traffic
* No sound effects/modifiers possible, due to the lack of proper libbass bindings (?)
* No linux support (has this changed?)

@Python1320 what do you think about this?

**Comment by X-Coder** [comment]
You are right about the points you listed, don't know about how far bass has linux support.

I used the patch on my windows server for half a year, on a 16 slot server. Traffic increases only on the webserver side because each client need to download the files before playing, but most of them are small, so no big issue. Could be different on a higher populated server like metastruct.

Bad Latency - maybe for people with no good connection while downloading the files, didn't get any complains yet on my server.

The biggest issue for you is, the not working modifiers - if it is not supported by garry's bass implementation. You can find a list of functions supported by garrysmod here: http://wiki.garrysmod.com/page/Category:IGModAudioChannel.
It seems to have SetPlaybackRate and SetVolume.

**Comment by PotcFdk** [comment]
By latency I meant the time between typing the sound names and actually hearing them; in the order you used them, with the correct effects applied to each sound. You could pre-load all sounds of a message, which would significantly increase the time before the first sound is played, or, alternatively, load them "just-in-time", which causes noticeable, uncontrollable gaps between sounds.

Also note, that we support more than just setting the playback rate and volume of a sound: http://wiki.garrysmod.com/page/CSoundPatch/SetDSP

**Comment by Noiwex** [comment]
I'd use workshop to make custom packs.

**Comment by Noiwex** [comment]
it will be implemented but in different way

**Comment by PotcFdk** [comment]
Note: there is no specific plan to change this. 
Whatever @Noiwex is referring to is _not_ known to other people than him; at least not according to my information.

**Comment by Noiwex** [comment]
your sound collection will be remained intact, chatsounds code base will be more efficient and extendible, supporting multiple sound collections, without even a need to commit them here (probably)
