### ISSUE TITLE
Chatsounds starting with numbers followed by a letter get parsed incorrectly

### ISSUE THREAD

**Issue by TW1STaL1CKY** [Metastruct/garrysmod-chatsounds#245]
Chatsounds that start with any amount of numbers then immediately followed by a letter don't get parsed correctly, like "100abc", so the wrong chatsound gets played.

If a space is between the numbers and the letters, it will parse, like "1800 contacts".
It does not matter where in the chat message the bad chatsound is.

**Previous example:**
_ukgamer tried adding a chatsound named "80sremix", but all that would get played is "8"._

**Current example:**
_The chatsound "90s music" - all that gets played is "9"._

**Comment by SpiralP** [comment]
I tried to tackle this at one point in time but gave up

I think it's somewhere in `build_word_list` https://gitlab.com/CapsAdmin/goluwa/-/blob/develop/game/lua/libraries/audio/chatsounds/chatsounds.lua#L282

just found some old code trying to fix it but I don't think it worked in the end

```lua
string.getchartype = goluwa.env.string.getchartype

local function build_word_list(str)
	local words = {}
	local temp = {}
	local last = string.getchartype(str:sub(1,1))
	local exp = false
	local exp_level = 0
	local capture_exp = true
	local bracket_level = 0

	for i = 1, #str + 1 do
		local char = str:sub(i,i)
		local next = str:sub(i+1, i+1)
		local type = string.getchartype(char)

			
			if type == "digit" and (last == "digit" or last == "letters" or string.getchartype(next) == "letters" or string.getchartype(next) == "digit") then
				type = "letters"
			end

			if not exp and (type ~= last or char == ":" or char == ")" or char == "(" or char == ",") or capture_exp then
				local word = table.concat(temp, "")
				if #word > 0 then
					table.insert(words, table.concat(temp, ""))
					table.Empty(temp)
				end
				capture_exp = nil
			end

			table.insert(temp, char)

		last = type
	end

	return words
end

p(
	build_word_list("helloh++50")
)
```

**Comment by Earu** [comment]
@TW1STaL1CKY with today's addition of [neo-chatsounds](https://github.com/Earu/neo-chatsounds) this shouldn't happen anymore, although I don't if this issue was related to the goluwa version or to the old local-only version in this repo.
