### ISSUE TITLE
Can anyone help me how to make a sound list to add sounds? 

### ISSUE THREAD

**Issue by ColinRafaelPerez08** [Metastruct/garrysmod-chatsounds#269]
I'm currently trying to add some sounds, but when I was reading the instructions on how to do it, I got confused as to what to do.

**Comment by Cynosphere** [comment]
If you have a pull request merged, one will automatically be created shortly after the commit via MetaAutomator

If you really need to for whatever reason you can just run chatsounds-preprocessor.exe
