### ISSUE TITLE
Portal 1 and Portal 2 dialog chatsounds

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#31]

**Comment by SpiralP** [comment]
would need to use sound.PlayFile instead of EmitSound like we are now, since they are like .mp3's named as .wav's :/

**Comment by SpiralP** [comment]
just checked again `$ file ambient/dinosaur_fizzle.wav vo/aperture_ai/01_part1_get_portal_gun-1.wav
ambient/dinosaur_fizzle.wav:                  RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
vo/aperture_ai/01_part1_get_portal_gun-1.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
` I can't remember what was wrong actually :v but most don't play

**Comment by SpiralP** [comment]
fack, these buttons are so bad, it should be cancel there like it is when editing :<
I think it was that the vpk is an older version or something because some of the files end up showing as 0 bytes

**Comment by LUModder** [comment]
Could we just take the hard way out and port? I mean, yeah it kills space but at least people without the games will have them

**Comment by SpiralP** [comment]
sound/vo/ is 150MB :v:

**Comment by PotcFdk** [comment]
Please don't.
