### ISSUE TITLE
Gourgeous Freeman chatsounds

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#35]
https://www.youtube.com/watch?v=aqRUjjuUl7U
https://www.youtube.com/watch?v=l1SvvagUGuU

**Comment by Vuthakral** [comment]
Sorry, I keep getting distracted. I'll just have to leave this to someone else.

**Comment by Vuthakral** [comment]
I was coming to look at the issues on chatsounds and I see this is still open. Whoever committed these chatsounds a while back didn't close this issue.
