### ISSUE TITLE
spaces don't work in chatsound folder names

### ISSUE THREAD

**Issue by TrenchFroast** [Metastruct/garrysmod-chatsounds#40]
This has been going on for quite a while now. They used to work at one point.

**Comment by SpiralP** [comment]
I changed your LCL back to LUA since people without chatsounds downloaded sometimes can't see the files with LCL
Still can hear sounds from folders with spaces, so I think we're good

**Comment by PotcFdk** [comment]
@SpiralP committed 7544e8714358a530fbeec750e42c8a1cd9d385d1
@TrenchFroast can you check whether this brought back the bug?

**Comment by TrenchFroast** [comment]
@PotcFdk i dont have the time + im kinda off gmod right now

**Comment by PotcFdk** [comment]
@SpiralP 
>since people without chatsounds downloaded

They don't have the custom files anyways, now, do they? So they shouldn't care about `lists_nosend`. Wouldn't it be enough to just change `lists_send` instead of both? Please explain your commit.

**Comment by SpiralP** [comment]
yeah, lists_send wasn't showing up at all, along with other lua/chatsounds/.lua files with LCL, but it used to work so that if you had tf2 but not the custom sounds you could still autocomplete them and hear them
I've tried some michael rosen ones, they autocomplete and I can hear them currently

**Comment by PotcFdk** [comment]
>they autocomplete and I can hear them currently
