### ISSUE TITLE
Remove/Change name of autoadd\tf2extra\lol.ogg

### ISSUE THREAD

**Issue by Vuthakral** [Metastruct/garrysmod-chatsounds#46]
Or at least rename it so it doesnt override the most common chatsound I hear in the game. I'm not one to bitch about chatsounds' content and what's in it, but this sound is unpleasent to hear and it overrides probably one of the most common chatsounds played in Gmod, it is #1 in the list of "lol" chatsounds and has become the most common one to hear. I'd do it myself but I'd at least run the idea by everyone else before doing it, in the event someone would actually care for this god-awful sound.

**Comment by PotcFdk** [comment]
Sounds awful to me as well, I'm all for the removal.

**Comment by TrenchFroast** [comment]
i'll rename it to lul

**Comment by TrenchFroast** [comment]
fixed with commit a3d0e9b
