### ISSUE TITLE
Chatsounds links are 404

### ISSUE THREAD

**Issue by venomousbendy** [Metastruct/garrysmod-chatsounds#460]
[audio][chatsounds] change detected https://raw.githubusercontent.com/PAC3-Server/chatsounds-valve-games/master/ep2/
[audio][chatsounds] loaded 0 unqiue sounds from https://raw.githubusercontent.com/PAC3-Server/chatsounds-valve-games/master/ep2/
[audio][chatsounds] found cached list but format doesn't look right, regenerating.
[audio][chatsounds] change detected https://raw.githubusercontent.com/PAC3-Server/chatsounds-valve-games/master/l4d2/
[audio][chatsounds] loaded 0 unqiue sounds from https://raw.githubusercontent.com/PAC3-Server/chatsounds-valve-games/master/l4d2/

Is the error I'm getting

**Comment by Cynosphere** [comment]
Not related to this repo, this repo is only for sounds nowadays and its code content has never referred to other sound repos.

**Comment by venomousbendy** [comment]
> Not related to this repo, this repo is only for sounds nowadays and its code content has never referred to other sound repos.

oh ok
