### ISSUE TITLE
647 sounds, 40,6 MB of sounds in total

### ISSUE THREAD

**Issue by zxz41** [Metastruct/garrysmod-chatsounds#47]
Stanley Parable narrator qoutes, translated from the offical game (using cc_find)
Can I upload this? No I'm not going to go thru all the trouble of making a fork for this .-.

https://dl.dropboxusercontent.com/u/31317176/CHATSOUND/Boss_delay_3_01.ogg

and stanley got the hell along with the story well whoop de doo

**Comment by TrenchFroast** [comment]
if this is rejected just add a random selection of the sounds ;D
