### ISSUE TITLE
More ChoZo chatsounds

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#49]
https://www.youtube.com/watch?v=sfCiOzL7cYs

**Comment by zxz41** [comment]
![wpxikmgydnaveaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/11709919/12238082/7f5de2fa-b882-11e5-8172-d5c8a2c7e165.png)

**Comment by LUModder** [comment]
Fixed

**Comment by LUModder** [comment]
Meant fixed link, no one added the sounds
