### ISSUE TITLE
Certain chatsounds don't work on linux

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#54]
09:12 - KaosHeaven: i figured out why certain files dont work with chatsounds on linux
09:12 - KaosHeaven: the lua lists are sometimes capped
09:13 - KaosHeaven: and gmods file system on linux doesnt read capital letters

We need to uncapitalize a lot of paths.

**Comment by Kaosheaven** [comment]
yeah linux filesystem (at least on mint) doesnt read capital letters

**Comment by TrenchFroast** [comment]
blame linux for case sensitive and blame valve for a shitty filesystem

**Comment by PotcFdk** [comment]
Actually, I think it's Garry's fault. IIRC, he just lowercases everything internally because #garry.

**Comment by LUModder** [comment]
Why blame people and JUST FIX IT

**Comment by TrenchFroast** [comment]
because we cant fucking find a fix that actually works??
i cant decapitalize file/folder names in the github app because **_it doesnt register it as a change._**

**Comment by LUModder** [comment]
Well the github app sucks in general, use tortousesvn then

**Comment by PotcFdk** [comment]
Oh, uh, I can fix it if you want.

**Comment by TrenchFroast** [comment]
why would i use svn with _github_, it's a fucking _GIT_ host not a svn host (and i dont care if you can pull changes using svn)

**Comment by Tenrys** [comment]
use sourcetree it's best gui app for git

**Comment by TrenchFroast** [comment]
@Tenrys :+1:

**Comment by PotcFdk** [comment]
The preprocessor now warns about paths that contain uppercase characters and will not integrate them into the lists anymore. At least now you shouldn't be able to accidentally add uppercase sound files.
