### ISSUE TITLE
iDubbbz Chatsounds

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#56]
https://www.youtube.com/playlist?list=PLHuzlz6-Ejx47YlyAAdlTfVC8iFKZUQod

https://www.youtube.com/channel/UC4USoIAL9qcsx5nCZV_QRnA

**Comment by zxz41** [comment]
https://youtu.be/ubK9inNVyxU?t=2s

**Comment by AgentWhatever** [comment]
Fine, il fucking do it
