### ISSUE TITLE
Single-letter chatsounds hate any modifier (was hate # modifier)

### ISSUE THREAD

**Issue by igniscitrinus** [Metastruct/garrysmod-chatsounds#70]
The interpreter just assumes "a#6" means "a 6" and that's pretty annoying
send help

**Comment by PotcFdk** [comment]
Can't reproduce. Are you up-to-date? Did it happen on Meta? Does the issue exist in singleplayer?

**Comment by LUModder** [comment]
You also can't use %100 or =0.1*250 on single letter sounds either.

**Comment by igniscitrinus** [comment]
Yeah, I'm up to date. I don't recall very well, but it might've happened at some point on Meta, maybe. As for the last part, Singleplayer is the only mode I've tested it on, I'll try it on a dedi in a while.

**Comment by PotcFdk** [comment]
I don't remember whether we actually investigated this further. Were we able to reproduce it? Is it still an issue?

**Comment by notcake** [comment]
i propose we delete all single letter chatsounds to resolve this issue

**Comment by LUModder** [comment]
Still an issue. It's only with chatsounds shorter or equal to 3 letters.

**Comment by notcake** [comment]
i propose we delete all chatsounds with 3 letters or fewer to resolve this issue

**Comment by TrenchFroast** [comment]
but ag and bo are best chatsounds D:
you could replace "h" with "gasp" though

**Comment by LUModder** [comment]
actually im wrong, it's only one letter chatsounds, ag, bo and op get to stay.

**Comment by notcake** [comment]
i propose we delete all chatsounds

**Comment by igniscitrinus** [comment]
pls no
In all seriousness, the problem really seems to just appear and disappear completely at random, at least on my end.

**Comment by PotcFdk** [comment]
I'll try to investigate this, but seeing as @igniscitrinus said that it happens randomly, it might be hard to reproduce.

**Comment by LUModder** [comment]
God this is hard to reproduce.
Doesn't work on Meta
Works on FlexBox

**Comment by PotcFdk** [comment]
@LUModder then go fix it.

**Comment by LUModder** [comment]
But I don't know why it's doing it on Meta

**Comment by PotcFdk** [comment]
>Doesn't work on Meta  
>why it's doing it on Meta

What is it, now?

**Comment by LUModder** [comment]
I meant why is it not doing it on Meta :v

**Comment by PotcFdk** [comment]
I am confused. Does the bug happen or not happen on meta? Does the bug happen or not happen in singleplayer? Does the bug happen or not happen elsewhere?

**Comment by mortenae** [comment]
I think i know when it happens. '6' happens to come before 'h' in chatsounds.SortedList. It works when you write 'g#6' ('g' happens to come before '6' in SortedList). GetScriptFromText looks for the first matching element in SortedList even if the match is really part of a modifier.

**Comment by LUModder** [comment]
Seems to be fixed

**Comment by PotcFdk** [comment]
@LUModder How so? I can't see any related commits? Can you link to them?

**Comment by LUModder** [comment]
I don't know how it's fixed though, but it just started working so, who knows what fixed it.

**Comment by igniscitrinus** [comment]
It's really difficult to reproduce but the problem indeed still happens, reopening

**Comment by PotcFdk** [comment]
If anyone knows how to reliably (or semi-reliably) reproduce/trigger this bug, please help us by sharing that information!

**Comment by Noiwex** [comment]
Irreproducible.
