### ISSUE TITLE
something's really wrong

### ISSUE THREAD

**Issue by TrenchFroast** [Metastruct/garrysmod-chatsounds#71]
just look at them
[Exhibit A](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/squid)
[Exhibit B](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/squiddistress)
[Exhibit C](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/squidfall)
[Exhibit D](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/squidhappy)
[Exhibit E](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/squidhurt)
[Exhibit F](https://github.com/Metastruct/garrysmod-chatsounds/tree/master/sound/chatsounds/autoadd/lixquid/woomy)

if you really can't see what's wrong, it's that there's two copies of each file with different capitalization
i think commit ca80a0b did this

**Comment by LUModder** [comment]
Honestly multisounds should just be numbered

**Comment by SpiralP** [comment]
the caps ones aren't really there when you download onto your computer, at least on my side

kind of same problem I had in https://github.com/Metastruct/garrysmod-chatsounds/issues/64#issuecomment-182097693

**Comment by PotcFdk** [comment]
@SpiralP That's because your definition of "your computer" means Windows, which doesn't support case sensitive filesystems.
I'll get rid of the uppercase characters in a minute, so the last remnants will be gone.
The preprocessor already flags paths with uppercase characters as invalid.
