### ISSUE TITLE
Request: uppercase.txt (or defined in map.txt)

### ISSUE THREAD

**Issue by zxz41** [Metastruct/garrysmod-chatsounds#78]
Instead of having "dummy distorted" or "dummy loud". We should have a system where if "soundfolder/dummy.ogg" is defined as "uppercase". It'll only play when it's typed out in "Caps Lock"

Example:

```
    L["dummy"] = {
        {
            path = "folderpath/dummy.ogg",
            length = 1.9051246643066,
            uppercase = true,
        },
    }
```

Basicly only added to the pool of chatsounds that might play when it's typed out as "STUPID".
I don't know if the sound should ignore the "uppercase" rule when defined using #number thing.

(No, this don't mean every loud chatsound should only trigger with uppercase just sayin.)

**Comment by LUModder** [comment]
seems useful

**Comment by Noiwex** [comment]
chatsounds are always case agnostic
