### ISSUE TITLE
chatsounds request

### ISSUE THREAD

**Issue by Mawkus** [Metastruct/garrysmod-chatsounds#81]
finis old penes http://puu.sh/osPeN/e44f70c12b.mp3
and
penes http://puu.sh/osPgv/65f019788c.mp3

**Comment by TrenchFroast** [comment]
done (0acd4d2)

**Comment by Techbot121** [comment]
moved it to a seperate dir, just in case (https://github.com/Metastruct/garrysmod-chatsounds/commit/94d2f65a2c2b96eb6673274af0236204342df13f)
