### ISSUE TITLE
*click* woooo (new h3h3)

### ISSUE THREAD

**Issue by LUModder** [Metastruct/garrysmod-chatsounds#82]
https://www.youtube.com/watch?v=EBbLPnQ-CEw

**Comment by Techbot121** [comment]
if you want a specific part of a video, or whatever as a sound request, link the time to that part.

Don't force people to watch a 20min video.

**Comment by LUModder** [comment]
8:52 - on cnn, hard hitting memes
9:55 - click wooo
11:27 - his phone is his shoe
14:04 - hello this is a shoe

**Comment by guuurgle** [comment]
test

**Comment by guuurgle** [comment]
test2
