### ISSUE TITLE
Add more Mass Effect chatsounds

### ISSUE THREAD

**Issue by notcake** [Metastruct/garrysmod-chatsounds#9]
There aren't enough Mass Effect chatsounds that aren't from shitty YouTube poops.

(https://www.youtube.com/watch?v=1YhqIM4nWso)
- Geth do not infiltrate.
- Geth do not intentionally infiltrate.

(https://youtu.be/lOHVdOCl8jk?t=48s)
- This conversation is over.
- I have a shotgun.

(https://www.youtube.com/watch?v=Q_ogInpxrqk)
- I enjoy the sight of humans on their knees.
- That is a joke.

Add more to this list please.
Rip from game files if possible, not YouTube.

**Comment by Vuthakral** [comment]
Everything is from the ingame files except "I enjoy humans on their knees" scene and the "Geth do not infiltrate" scene. Could not locate their files :/
Also added the files.
